version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: notes_db
    ports:
      - "3306:3306"
    networks:
      - my-network
  
  frontend:
    image: aryanbhatt1812/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
  
  
  backend:
    image: "aryanbhatt1812/backend:latest"
    ports:
      - "8085:8085"
    depends_on:
      - mysqldb
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/notes_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql@123
    # volumes:
    #   - /logs:/logs
    networks:
      - my-network

volumes:
  mysql-data:
    driver: local

networks:
  my-network:
    driver: bridge
